config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :tags

  map.resources :disclosures

  map.resources :schedules

  map.resources :contents

  map.resources :folders

  map.resources :users

  map.resources :calendar

  map.resources :profiles

  map.resources :gtd_projects

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/folder.rb
# -*- coding: utf-8 -*-
class Folder < ActiveRecord::Base

  # RELATIONSHIPS
  belongs_to :user
  belongs_to :disclosure
  has_many :contents, :order => 'created_at ASC'

  # VALIDATES
  validates_presence_of :name, :user_id
  validates_numericality_of :list_flag
  validate :valid_list_number, :uniqueness_name_each_user

  # CONSTANTS
  DISPLAY = 0
  HIDDEN  = 1
  LISTING = ['表示', '非表示']

  # METHODS
  def self.listing
    [[LISTING[DISPLAY], DISPLAY], [LISTING[HIDDEN], HIDDEN]]
  end

  def self.list(user_id)
    Folder.find(:all, :conditions => ['user_id = ?', user_id]).map {|f|
      [f.name, f.id]
    }
  end

  def browsable?(user_id)
    disclosure.browsable?(user_id)
  end

  def linkable?(user_id)
    disclosure.linkable?(user_id)
  end

  def editable?(user_id)
    disclosure.editable?(user_id)
  end

  def sharable?(user_id)
    disclosure.editable?(user_id)
  end

  def owner?(user_id)
    disclosure.owner?(user_id)
  end

  private

  def uniqueness_name_each_user
    return if id != nil
    folder = Folder.find_by_name_and_user_id(name, user_id)
    errors.add(:name, "既に同名のフォルダが登録されています") if !folder.nil?
  end

  def valid_list_number
    errors.add(:list_flag, "は正しいフラグ値ではありません") if (list_flag.nil? || LISTING[list_flag] == nil)
  end

end

app/models/profile.rb
class Profile < Coa3Application

  # CONSTANTS
  MAIL_ADDRESS = 'mail_address'
  GTD_PROJECT_FOLDER = 'gtd_project_folder'
  GTD_INBOX = 'gtd_inbox'

  def Profile.mimetype
    MIMETYPE_BASE + 'profile'
  end

  #def mimetype
  #  MIMETYPE_BASE + 'profile'
  #end

  def mail_address
    get(MAIL_ADDRESS)
  end

  def mail_address=(addr)
    set(MAIL_ADDRESS, addr)
  end

  def gtd_project_folder
    get(GTD_PROJECT_FOLDER)
  end

  def gtd_project_folder=(folderid)
    set(GTD_PROJECT_FOLDER, folderid)
  end

  def gtd_inbox
    get(GTD_INBOX)
  end

  def gtd_inbox=(contentid)
    set(GTD_INBOX, contentid)
  end

end

app/controllers/folders_controller.rb
# -*- coding: utf-8 -*-
class FoldersController < ApplicationController
  # GET /folders
  # GET /folders.xml
  def index
    session[:folder_id] = nil
    #login = User.find(session[:user_id])
    #@folders = login.folders
    @folders = []
    Folder.find(:all, :order => 'user_id, sequence, name').each do |f|
      if f.disclosure == nil
        @folders << f if f.user_id == session[:user_id]
      else
        next if f.disclosure.privilege(session[:user_id]) < Grant::BROWSABLE
        @folders << f
      end
    end
    @title = 'フォルダ管理'

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @folders }
    end
  end

  # GET /folders/1
  # GET /folders/1.xml
  def show
    user = User.find(session[:user_id])
    @folders = user.folders
    @folder = Folder.find(params[:id])
    @priv = @folder.disclosure.privilege(session[:user_id])
    session[:folder_id] = @folder.id
    #@contents = @folder.contents
    @contents = @folder.contents.all(:order => 'title ASC')
    @title = 'フォルダ: ' + @folder.name

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @folder }
    end
  end

  # GET /folders/new
  # GET /folders/new.xml
  def new
    @folder = Folder.new
    @title = 'フォルダ作成'

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @folder }
    end
  end

  # GET /folders/1/edit
  def edit
    @folder = Folder.find(params[:id])
    session[:folder_id] = @folder.id
  end

  # POST /folders
  # POST /folders.xml
  def create
    @folder = Folder.new(params[:folder])

    respond_to do |format|
      if @folder.save
        flash[:notice] = "フォルダ [#{@folder.name}] が作成されました"
        format.html { redirect_to(:action => 'index') }
        format.xml  { render :xml => @folder, :status => :created, :location => @folder }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @folder.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /folders/1
  # PUT /folders/1.xml
  def update
    @folder = Folder.find(params[:id])

    respond_to do |format|
      if @folder.update_attributes(params[:folder])
        flash[:notice] = "フォルダ [#{@folder.name}] が更新されました"
        format.html { redirect_to(:action => 'index') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @folder.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.xml
  def destroy
    @folder = Folder.find(params[:id])
    @folder.destroy
    session[:folder_id] = nil

    respond_to do |format|
      format.html { redirect_to(folders_url) }
      format.xml  { head :ok }
    end
  end

  def move
    #flash[:notice] = "folder_id=#{params[:folder][:id]}"
    flash[:notice] = "selectitem=#{params['select'].keys.join(',')}"
    folder = Folder.find(params[:folder][:id])
    if folder != nil
      cons = Content.find(params['select'].keys,
                          :conditions => ['user_id = ?', session[:user_id]])
      cons.each do |c|
        c.folder = folder
        c.save
      end
    end

    respond_to do |format|
      format.html { redirect_to(:action => 'show', :id => session[:folder_id]) }
      format.xml { head :ok }
    end
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/edit.html.erb
<%= link_to '表示', @folder %> |
<%= link_to '一覧', folders_path %>
<hr>

<% form_for(@folder) do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :user_id, :value => session[:user_id] %>

  <table width="100%">
    <tr>
      <th width="100px">フォルダ名</th>
      <td><%= f.text_field :name, :size => 50 %></td>
    </tr>
    <tr>
      <th>公開設定</th>
      <td>
        <%= f.select :disclosure_id, Disclosure.list(session[:user_id]) %>
      </td>
    </tr>
    <tr>
      <th>表示順</th>
      <td><%= f.text_field :sequence, :size => 8 %></td>
    </tr>
    <tr>
      <th>表示フラグ</th>
      <td><%= f.select :list_flag, Folder.listing %></td>
    </tr>
  </table>

  <p>
    <%= f.submit '更新' %>
  </p>
<% end %>

app/views/folders/index.html.erb
<%= link_to 'フォルダ作成', new_folder_path %>
<hr>

<table width="100%">
  <tr>
    <th width="50px">操作</th>
    <th>フォルダ</th>
    <th width="80px">コンテンツ数</th>
    <th width="120px">権限</th>
    <th width="50px">表示順</th>
    <th>表示</th>
  </tr>

<% @folders.each do |folder| %>
  <tr>
    <td>
      <% if folder.owner?(@login.id) && folder.contents.size == 0 %>
        <%= link_to (image_tag 'delete12.gif'), folder,
	  :confirm => '本当に削除してよいですか?', :method => :delete %>
      <% end %>
    </td>
    <td>
      <span class="<%= if folder.editable?(@login.id) then 'mine'
                       else 'others' end %>">
        <%= link_to h(folder.name), folder %>
      </span>
    </td>
    <td align="right"><%= folder.contents.size %></td>
    <td>
      <%= Grant::PRIVS[folder.disclosure.privilege(session[:user_id])] %>
      <% if folder.user.id != @login.id %>
        (<%= folder.user.name %>)
      <% end %>
    </td>
    <td align="right"><%= folder.sequence %></td>
    <td>
      <% if folder.list_flag == 0 %>
      <%= "表示" %>
      <% else %>
      <%= "非表示" %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

app/views/folders/new.html.erb
<%= link_to '一覧', folders_path %>
<hr>

<% form_for(@folder) do |f| %>
  <%= f.error_messages %>

  <%= f.hidden_field :user_id, :value => session[:user_id] %>

  <table width="100%">
    <tr>
      <th width="100px">フォルダ名</th>
      <td><%= f.text_field :name, :size => 50 %></td>
    </tr>
    <tr>
      <th>公開設定</th>
      <td>
        <%= f.select :disclosure_id, Disclosure.list(session[:user_id]) %>
      </td>
    </tr>
    <tr>
      <th>表示順</th>
      <td><%= f.text_field :sequence, :size => 8 %></td>
    </tr>
    <tr>
      <th>表示フラグ</th>
      <td><%= f.select :list_flag, Folder.listing %></td>
    </tr>
  </table>

  <p>
    <%= f.submit '作成' %>
  </p>
<% end %>

app/views/folders/show.html.erb
<%= link_to '一覧', folders_path %> |
<% if @priv >= Grant::EDITABLE %>
  <%= link_to '編集', edit_folder_path(@folder) %> |
  <%= link_to 'コンテンツ作成', :controller => 'contents', :action => 'new' %>
<% end %>
<hr>

<% form_tag :action => 'move' do %>
  <%= collection_select :folder, :id, @folders, :id, :name %>
  <%= submit_tag '移動', :disable_with => '実行中です・・・',
    :confirm => '本当に移動してよいですか?' %>
  <p>
  <table width="100%">
    <tr>
      <th width="50px">操作</th>
      <th>タイトル</th>
      <th width="80px">公開(権限)</th>
      <th width="80px">最終アクセス</th>
      <th width="50px">サイズ</th>
    </tr>
    <% @contents.each do |content| %>
    <% next if content.disclosure.privilege(session[:user_id]) < Grant::BROWSABLE %>
    <tr>
      <td>
	<% if content.sharable?(@login.id) %>
          <%= check_box_tag "select[#{content.id}]", 'yes', false %>
          <%= link_to (image_tag 'delete12.gif'), content,
	      :confirm => '本当に削除してよいですか?', :method => :delete %>
	<% end %>
      </td>
      <td><%= link_to h(content.title), content %></td>
      <td>
        <% if content.user_id == session[:user_id] %>
          <%= content.disclosure.name %>
        <% else %>
          (<%= Grant::PRIVS[content.disclosure.privilege(session[:user_id])] %>)
        <% end %>
      </td>
      <td><%= content.last_access %></td>
      <td align="right"><%=h content.size_with_unit %></td>
    </tr>
    <% end %>
  </table>
<% end %>
</p>